nome = str(input("Digite Seu Nome Completo: ")).strip()
nome_separado = (nome.split())
print(f"SEU NOME EM MAIUSCULO E {nome.upper()}")
print(f"seu nome em minusculo e {nome.lower()}")
print("seu nome ao todo tem ", end=" ")
print(len(nome), end=" ")
print("caracteres")
print(nome.split())
print("O SEU NOME SEPARADO TEM " , end="")
print(len(nome_separado[0]), end="")
print(" UNIDADES")